var CommentConstants = {
  POST: "POST",
  ALL_COMMENTS: "ALL_COMMENTS",
  SHOW_ERRORS: "SHOW_ERRORS",
  RECEIVE_COMMENT: "RECEIVE_COMMENT",
  REMOVE_COMMENT: "REMOVE_COMMENT"
};

module.exports = CommentConstants;
